# Generated by Django 3.1.2 on 2020-10-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_like_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'post')},
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
