# Generated by Django 3.1.2 on 2020-11-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20201102_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_image'),
        ),
    ]
