# Generated by Django 3.1.2 on 2020-11-02 12:46

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20201102_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='default.jpg', upload_to='profile_image'),
        ),
    ]
